services:
  web:
    build: .
    environment:
      SECRET_KEY: 'django-insecure-%p6n6sss5kk!p*_j&7)nw#r5$5y3mo2^lv*l8*e)fvy^zt2s7_'
      GITHUB_KEY: 'Ov23lisNOOUseR88CGdI'
      GITHUB_SECRET: '122ed14bcef93411fa64475084fd2f1afa45a992'
      GOOGLE_OAUTH2_KEY: '78859909082-4gr9ih17rt5o9dv71s11be4msm9401j0.apps.googleusercontent.com'
      GOOGLE_OAUTH2_SECRET: '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'
      EMAIL_USER: 'eng.alihasanahmad@gmail.com'
      EMAIL_PASSWORD: 'txjwcfqxhwsylgja'

    volumes:
      - .:/code

  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
    depends_on:
      - db

  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - web_migrate

  db:
    image: postgres:12.20-bullseye
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB= blog_api
      - POSTGRES_USER=blog_api
      - POSTGRES_PASSWORD=blog_api
